# Site settings
title: Dogan Kilic
tag_text: <i class="fa fa-at" aria-hidden="true"></i>Dogan Kilic - Android Developer
description: Android developer
url: https://dnkilic.github.io

# Build settings
markdown: kramdown
exclude: ["README.md", "old/"]
sass:
  style: compressed

plugins_dir:
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-github-metadata
  # - jekyll-avatar

# contact_links:
#   - name: LinkedIn
#     url: https://www.linkedin.com/in/dnkilic
#     icon: linkedin
#   - name: GitHub
#     url: https://github.com/dnkilic
#     icon: github
#   - name: Medium
#     url: https://medium.com/@dnkilic
#     icon: medium
